version: '3.8'

services:
  # 1. Adatbázis (PostgreSQL) - A Catalog és Booking servicek adatainak
  ticket-db:
    image: postgres:15-alpine
    container_name: ticket-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ticketmaster
    ports:
      - "5432:5432"  # Kivezetjük, hogy a Visual Studio elérje
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  # 2. Gyorsítótár (Redis) - A foglalások és készlet gyors kezeléséhez
  ticket-cache:
    image: redis:alpine
    container_name: ticket-cache
    ports:
      - "6379:6379"
    restart: always

  # 3. Üzenetküldő (RabbitMQ) - A Booking és Notification közötti kommunikációhoz
  ticket-rabbit:
    image: rabbitmq:3-management
    container_name: ticket-rabbit
    ports:
      - "5672:5672"   # Applikáció kommunikáció
      - "15672:15672" # Adminisztrációs felület (böngésző)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always

volumes:
  postgres-data: