# --- INFRASTRUKTÚRA ---
postgresql:
  image:
    repository: postgres
    tag: "15-alpine"
  password: postgres

redis:
  image:
    repository: redis
    tag: "alpine"

rabbitmq:
  image:
    repository: rabbitmq
    tag: "3-management"
  username: guest
  password: guest
# --- SAJÁT SZOLGÁLTATÁSOK ---
# A képeket továbbra is a Docker Hub-ról szedjük (lásd előző lépések)

catalog:
  image:
    repository: ppeti1999/ticketmaster-catalog
    tag: "v1"
    pullPolicy: IfNotPresent
  replicaCount: 1
  servicePort: 8080
  # Connection String a Bitnami Postgres-hez:
  # Host: my-postgres-postgresql (ez a helm install neve + a chart neve)
  connectionString: "Host=my-postgres-postgresql;Port=5432;Database=ticketmaster;Username=postgres;Password=postgres;"

booking:
  image:
    repository: ppeti1999/ticketmaster-booking
    tag: "v1"
    pullPolicy: IfNotPresent
  replicaCount: 1
  servicePort: 8080
  # Postgres kapcsolat
  connectionString: "Host=my-postgres-postgresql;Port=5432;Database=ticketmaster;Username=postgres;Password=postgres;"
  # Redis kapcsolat (Bitnami service neve: my-redis-master)
  redisConnection: "my-redis-master:6379"
  # RabbitMQ kapcsolat
  rabbitHost: "my-rabbitmq"
  rabbitUser: "guest"
  rabbitPass: "guest"

worker:
  image:
    repository: ppeti1999/ticketmaster-worker
    tag: "v1"
    pullPolicy: IfNotPresent
  replicaCount: 1
  rabbitHost: "my-rabbitmq"
  rabbitUser: "guest"
  rabbitPass: "guest"