apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: {{ .Values.analytics.image.repository }}:{{ .Values.analytics.image.tag }}
          imagePullPolicy: {{ .Values.analytics.image.pullPolicy }}
          env:
            # --- Mongo Connection ---
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: ticketmaster-config
                  key: mongo-host
            - name: ConnectionStrings__MongoDb
              value: "mongodb://$(MONGO_HOST):27017" # Változó behelyettesítés

            # --- RabbitMQ Config (ConfigMap + Secret) ---
            - name: RabbitMQ__Host
              valueFrom:
                configMapKeyRef:
                  name: ticketmaster-config
                  key: rabbit-host
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: ticketmaster-secret
                  key: rabbit-user
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: ticketmaster-secret
                  key: rabbit-pass