apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jwt-auth
spec:
  forwardAuth:
    # A belső K8s DNS nevet használjuk: auth-service service név + port
    address: http://auth-service:8080/api/Auth/validate
    trustForwardHeader: true
