apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
spec:
  replicas: {{ .Values.booking.replicaCount }}
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: "{{ .Values.booking.image.repository }}:{{ .Values.booking.image.tag }}"
          imagePullPolicy: {{ .Values.booking.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            # --- 1. Postgres (Ugyanaz a tr√ºkk) ---
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ticketmaster-config
                  key: postgres-host
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ticketmaster-secret
                  key: postgres-pass
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ticketmaster-secret
                  key: postgres-user
            - name: ConnectionStrings__DefaultConnection
              value: "Host=$(DB_HOST);Port=5432;Database=ticketmaster;Username=$(DB_USER);Password=$(DB_PASS);"

            # --- 2. Redis ---
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: ticketmaster-config
                  key: redis-host
            - name: ConnectionStrings__Redis
              value: "$(REDIS_HOST):6379"

            # --- 3. RabbitMQ ---
            - name: RabbitMQ__Host
              valueFrom:
                configMapKeyRef:
                  name: ticketmaster-config
                  key: rabbit-host
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: ticketmaster-secret
                  key: rabbit-user
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: ticketmaster-secret
                  key: rabbit-pass
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.booking.nodePort }}
  selector:
    app: booking