apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: {{ .Values.catalog.replicaCount }}
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          # LABOR TECHNIKA: Összefűzés
          image: "{{ .Values.catalog.image.repository }}:{{ .Values.catalog.image.tag }}"
          imagePullPolicy: {{ .Values.catalog.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            # --- Adatbázis Változók ---
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ticketmaster-config
                  key: postgres-host
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ticketmaster-secret
                  key: postgres-pass
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ticketmaster-secret
                  key: postgres-user
            
            # --- Connection String összerakása ---
            - name: ConnectionStrings__DefaultConnection
              value: "Host=$(DB_HOST);Port=5432;Database=ticketmaster;Username=$(DB_USER);Password=$(DB_PASS);"
            - name: JWT__Key
              value: "EzEgyNagyonHosszuEsTitkosKulcsAmiLegalabb32Karakter2026"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service # Fix név, hogy a Booking megtalálja
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.catalog.nodePort }}
  selector:
    app: catalog