apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketmaster-config
data:
  # Szolgáltatásnevek (ezek nem titkosak)
  rabbit-host: "rabbitmq"
  postgres-host: "ticketmaster-db"
  mongo-host: "ticketmaster-mongo"
  redis-host: "ticketmaster-redis"