apiVersion: v1
kind: Secret
metadata:
  name: ticketmaster-secret
type: Opaque
stringData:
  # Jelszavak (a Helm automatikusan titkosítja/kódolja őket)
  rabbit-user: "guest"
  rabbit-pass: "guest"
  postgres-user: "postgres"
  postgres-pass: "postgres"