apiVersion: v1
kind: Secret
metadata:
  name: ticketmaster-secret
type: Opaque
stringData:
  # A jelszavakat ide szervezzÃ¼k ki
  rabbit-user: "guest"
  rabbit-pass: "guest"
  postgres-user: "postgres"
  postgres-pass: "postgres"