global:
  imagePullPolicy: IfNotPresent

# --- INFRASTRUKTÚRA ---
postgresql:
  image:
    repository: postgres
    tag: "15-alpine"
  password: postgres

redis:
  image:
    repository: redis
    tag: "alpine"

rabbitmq:
  image:
    repository: rabbitmq
    tag: "3-management"
  username: guest
  password: guest
# --- SAJÁT SZOLGÁLTATÁSOK ---

catalog:
  image:
    repository: ppeti1999/ticketmaster-catalog
    tag: "v1"
    pullPolicy: IfNotPresent
  replicaCount: 1
  servicePort: 8080
  # ÚJ Connection String a saját Postgres-hez (ticketmaster-db):
  connectionString: "Host=ticketmaster-db;Port=5432;Database=ticketmaster;Username=postgres;Password=postgres;"

booking:
  image:
    repository: ppeti1999/ticketmaster-booking
    tag: "v1"
    pullPolicy: IfNotPresent
  replicaCount: 1
  servicePort: 8080
  # Postgres kapcsolat
  connectionString: "Host=ticketmaster-db;Port=5432;Database=ticketmaster;Username=postgres;Password=postgres;"
  # Redis kapcsolat (ticketmaster-redis)
  redisConnection: "ticketmaster-redis:6379"
  # RabbitMQ kapcsolat (my-rabbitmq a neve a te rabbitmq.yaml fájlodban)
  rabbitHost: "my-rabbitmq"
  rabbitUser: "guest"
  rabbitPass: "guest"

worker:
  image:
    repository: ppeti1999/ticketmaster-worker
    tag: "v1"
    pullPolicy: IfNotPresent
  replicaCount: 1
  rabbitHost: "my-rabbitmq"
  rabbitUser: "guest"
  rabbitPass: "guest"

  # ... (a fájl vége)

analytics:
  image:
    repository: ppeti1999/ticketmaster-analytics
    tag: "v1"
    pullPolicy: IfNotPresent
  rabbitHost: "my-rabbitmq"  # FONTOS: Ez legyen ugyanaz, mint a rabbitmq.yaml metadata.name értéke!
  rabbitUser: "guest"
  rabbitPass: "guest"
auth:
  replicaCount: 1
  image:
    repository: ppeti1999/ticketmaster-auth
    tag: "v1"
  service:
    port: 8080